### ISSUE TITLE
Migrate to new way datetimes are localized

### ISSUE THREAD

**Issue by fmhoeger** [Dallinger/Dallinger#3841] opened 2022-02-18 20:00 UTC
Get rid of following warnings in the log output:

`PytzUsageWarning: The localize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html`

**Comment by jessesnyder** [comment] 2022-02-18 20:19
This is a duplicate of https://github.com/Dallinger/Dallinger/issues/3793

**Closed by jessesnyder** 2022-02-18 20:19 UTC
Labels: duplicate

**Comment by fmhoeger** [comment] 2022-02-18 20:21
Yes, just recognized that, too.
