### ISSUE TITLE
Run from within a Jupyter Notebook

### ISSUE THREAD

**Issue by suchow** [Dallinger/Dallinger#653] opened 2017-06-28 10:58 UTC
When the following code is run from a `demo.py` file or from the Python interpreter, it runs as expected, collecting a new dataset. However, when run from within a Jupyter Notebook, it complains that `KeyError: u'dallinger_email_password is not a valid configuration key'`.

```
import dallinger

experiment = dallinger.experiments.Bartlett1932()
data = experiment.collect(
    app_id=u"3b9c2aeb-0eb7-4432-803e-bc437e17b3bb",
)
print(data.networks.list)
```

Test files:

[demos.zip](https://github.com/Dallinger/Dallinger/files/1108404/demos.zip)

**Comment by suchow** [comment] 2017-06-28 20:10
Testing this again, I see a different error message the first vs. second time I run the script. Here's the first traceback:

```
>>>> Retrieve: Could not fetch data for id: 3b9c2aeb-0eb7-4432-803e-bc437e17b3bc, checking registry
>>>> Retrieve: 3b9c2aeb-0eb7-4432-803e-bc437e17b3bc appears to be a new experiment id, running experiment.

    ____        ____
   / __ \____ _/ / (_)___  ____ ____  _____
  / / / / __ `/ / / / __ \/ __ `/ _ \/ ___/
 / /_/ / /_/ / / / / / / / /_/ /  __/ /
/_____/\__,_/_/_/_/_/ /_/\__, /\___/_/
                        /____/
                                   v3.2.0

                Laboratory automation for
       the behavioral and social sciences.


IOErrorTraceback (most recent call last)
<ipython-input-1-ee5372275baf> in <module>()
      3 experiment = dallinger.experiments.Bartlett1932()
      4 data = experiment.collect(
----> 5     app_id=u"3b9c2aeb-0eb7-4432-803e-bc437e17b3bc",
      6 )
      7 print(data.networks.list)

/Users/jordansuchow/Dropbox/Berkeley/Projects/Current/Dallinger/dallinger/experiment.pyc in collect(self, app_id, exp_config, bot, **kwargs)
    531         self.log(u'{} appears to be a new experiment id, running experiment.'.format(app_id),
    532                  key=u"Retrieve:")
--> 533         return self.run(exp_config, app_id, bot, **kwargs)
    534 
    535     @classmethod

/Users/jordansuchow/Dropbox/Berkeley/Projects/Current/Dallinger/dallinger/experiment.pyc in new_meth(self, *args, **kwargs)
     45             config.register_extra_parameters()
     46             config.load_from_file(LOCAL_CONFIG)
---> 47             return meth(self, *args, **kwargs)
     48         finally:
     49             config._reset()

/Users/jordansuchow/Dropbox/Berkeley/Projects/Current/Dallinger/dallinger/experiment.pyc in run(self, exp_config, app_id, bot, **kwargs)
    485                 app=app_id,
    486                 verbose=self.verbose,
--> 487                 exp_config=self.exp_config
    488             )
    489         return self._finish_experiment()

/Users/jordansuchow/Dropbox/Berkeley/Projects/Current/Dallinger/dallinger/command_line.pyc in deploy_sandbox_shared_setup(verbose, app, web_procs, exp_config)
    416 
    417     (id, tmp) = setup_experiment(debug=False, verbose=verbose, app=app,
--> 418                                  exp_config=exp_config)
    419 
    420     # Register the experiment using all configured registration services.

/Users/jordansuchow/Dropbox/Berkeley/Projects/Current/Dallinger/dallinger/command_line.pyc in setup_experiment(debug, verbose, app, exp_config)
    250         public_id = str(app)
    251 
--> 252     log("Experiment id is " + public_id + "")
    253 
    254     # Copy this directory into a temporary folder, ignoring .git

/Users/jordansuchow/Dropbox/Berkeley/Projects/Current/Dallinger/dallinger/command_line.pyc in log(msg, delay, chevrons, verbose)
     66     if verbose:
     67         if chevrons:
---> 68             click.echo(u"\n❯❯ " + msg)
     69         else:
     70             click.echo(msg)

/usr/local/lib/python2.7/site-packages/click/utils.pyc in echo(message, file, nl, err, color)
    257 
    258     if message:
--> 259         file.write(message)
    260     file.flush()
    261 

/usr/local/lib/python2.7/site-packages/click/_compat.pyc in write(self, x)
     61                     pass
     62                 return self.buffer.write(str(x))
---> 63             return io.TextIOWrapper.write(self, x)
     64 
     65         def writelines(self, lines):

IOError: not writable
```

And here's the second traceback:

```
KeyErrorTraceback (most recent call last)
<ipython-input-2-ee5372275baf> in <module>()
      3 experiment = dallinger.experiments.Bartlett1932()
      4 data = experiment.collect(
----> 5     app_id=u"3b9c2aeb-0eb7-4432-803e-bc437e17b3bc",
      6 )
      7 print(data.networks.list)

/Users/jordansuchow/Dropbox/Berkeley/Projects/Current/Dallinger/dallinger/experiment.pyc in collect(self, app_id, exp_config, bot, **kwargs)
    505             )
    506             os.chdir(new_path)
--> 507             results = data_load(app_id)
    508             self.log(u'Data found for experiment {}, retrieving.'.format(app_id),
    509                      key=u"Retrieve:")

/Users/jordansuchow/Dropbox/Berkeley/Projects/Current/Dallinger/dallinger/data.pyc in load(app_id)
     96 def load(app_id):
     97     """Load the data from wherever it is found."""
---> 98     path_to_data = find_experiment_export(app_id)
     99     if path_to_data is None:
    100         raise IOError("Dataset {} could not be found.".format(app_id))

/Users/jordansuchow/Dropbox/Berkeley/Projects/Current/Dallinger/dallinger/data.pyc in find_experiment_export(app_id)
     79 
     80     buckets = [
---> 81         user_s3_bucket(),
     82         dallinger_s3_bucket(),
     83     ]

/Users/jordansuchow/Dropbox/Berkeley/Projects/Current/Dallinger/dallinger/data.pyc in user_s3_bucket(canonical_user_id)
    340 def user_s3_bucket(canonical_user_id=None):
    341     """Get the user's S3 bucket."""
--> 342     conn = _s3_connection()
    343     if not canonical_user_id:
    344         canonical_user_id = conn.get_canonical_user_id()

/Users/jordansuchow/Dropbox/Berkeley/Projects/Current/Dallinger/dallinger/data.pyc in _s3_connection(dallinger_region)
    381     config = get_config()
    382     if not config.ready:
--> 383         config.load()
    384 
    385     region = 'us-east-1' if dallinger_region else config.get('aws_region')

/Users/jordansuchow/Dropbox/Berkeley/Projects/Current/Dallinger/dallinger/config.pyc in load(self)
    216             globalConfig,
    217         ]:
--> 218             self.load_from_file(config_file)
    219 
    220         if os.path.exists(localConfig):

/Users/jordansuchow/Dropbox/Berkeley/Projects/Current/Dallinger/dallinger/config.pyc in load_from_file(self, filename)
    180         for section in parser.sections():
    181             data.update(dict(parser.items(section)))
--> 182         self.extend(data, cast_types=True, strict=True)
    183 
    184     def write(self, filter_sensitive=False):

/Users/jordansuchow/Dropbox/Berkeley/Projects/Current/Dallinger/dallinger/config.pyc in extend(self, mapping, cast_types, strict)
     99                 # This key hasn't been registered, we ignore it
    100                 if strict:
--> 101                     raise KeyError('{} is not a valid configuration key'.format(key))
    102                 logger.debug('{} is not a valid configuration key'.format(key))
    103                 continue

KeyError: u'dallinger_email_password is not a valid configuration key'
```

**Comment by MatthewWilkes** [comment] 2017-06-28 22:50
The IOError only seems to happen when writing extended characters, I wonder if the fake stdout that jupyter is providing is enforcing a character encoding. Looking into it.

**Comment by MatthewWilkes** [comment] 2017-06-28 23:47
The monkeypatch:

```from ipykernel.iostream import OutStream
OutStream.writable = lambda self:True```

prevents the first error. It seems that the OutStream object from ipykernel falsely declares that it will raise IOError on write, which the unicode fallback handling of click is raising. I'm not sure as to the root cause of it, but I'm making a note here so I don't forget.

**Comment by MatthewWilkes** [comment] 2017-06-29 00:02
Heroku local login is failing with inappropriate ioctl for device. That's causing the `finally` block in `exp_class_working_dir` to be called, which calls config._reset(). The reset method clears the config, but as it is stored in a threadlocal the jupyter kernel retains access to the (now empty) configuration.

I don't think `_reset` is a good choice here, I'm experimenting with doing `del configurations.config` as that will cause `get_config` to re-add the default config fields. Perhaps `_reset()` shouldn't remove the config items instead.

**Comment by MatthewWilkes** [comment] 2017-06-29 00:03
See also: https://stackoverflow.com/questions/31862983/pexpect-and-pycharm-inappropriate-ioctl-for-device - I'll look further tomorrow

**Comment by alecpm** [comment] 2017-06-29 02:22
Sounds like this is my fault. I'll take a look tomorrow.

**Comment by MatthewWilkes** [comment] 2017-06-29 08:27
@alecpm It looks to me like it's jupyter's web console that's the root cause of all this, by being marked as unwritable and by acting enough like a TTY to fool pexpect. The `_reset` call is just one step on the journey, fixing it still leaves us blocked

**Comment by suchow** [comment] 2017-07-15 19:04
@MatthewWilkes I don't see any issue with using your fork. The [pexpect license](https://github.com/pexpect/pexpect/blob/master/LICENSE) is permissive, and so if your contribution to pexpect is licensed under the same terms, it shouldn't pose any problems.

**Comment by MatthewWilkes** [comment] 2017-09-11 20:52
I've added PR 736 that works around this. Modifying pexpect turned out to be a rabbithole, it's not possible to support its functionality adequately well enough to make something useful. A lot of the same fixes needed were in common with @jessesnyder  #707 branch, which makes sense as they're both about getting useful information from subprocesses when not using a terminal.

**Closed** 2018-06-18 18:00 UTC
Labels: bug
