### ISSUE TITLE
No Infos from which to select the most recent

### ISSUE THREAD

**Issue by suchow** [Dallinger/Dallinger#1399] opened 2018-09-24 04:15 UTC
```
Sep 23 21:01:44 dlgr-183afda0 app/worker.1:  >>>> ----- Received an AssignmentSubmitted notification for assignment 326O153BMJRRVP1I6VLX3ZF0C7GEDV, participant None 
Sep 23 21:01:44 dlgr-183afda0 app/worker.1:  2018-09-24 04:01:44,215 Initializing MTurkRecruiter... 
Sep 23 21:01:44 dlgr-183afda0 app/worker.1:  2018-09-24 04:01:44,241 Starting new HTTPS connection (1): mturk-requester.us-east-1.amazonaws.com 
Sep 23 21:01:44 dlgr-183afda0 app/worker.1:  2018-09-24 04:01:44,485 Exception during scoped worker transaction, rolling back. 
Sep 23 21:01:44 dlgr-183afda0 app/worker.1:  Traceback (most recent call last): 
Sep 23 21:01:44 dlgr-183afda0 app/worker.1:    File "/app/.heroku/src/dallinger/dallinger/db.py", line 69, in sessions_scope 
Sep 23 21:01:44 dlgr-183afda0 app/worker.1:      yield local_session 
Sep 23 21:01:44 dlgr-183afda0 app/worker.1:    File "/app/.heroku/src/dallinger/dallinger/db.py", line 99, in wrapper 
Sep 23 21:01:44 dlgr-183afda0 app/worker.1:      return func(*args, **kwargs) 
Sep 23 21:01:44 dlgr-183afda0 app/worker.1:    File "/app/.heroku/src/dallinger/dallinger/experiment_server/experiment_server.py", line 1754, in worker_function 
Sep 23 21:01:44 dlgr-183afda0 app/worker.1:      runner() 
Sep 23 21:01:44 dlgr-183afda0 app/worker.1:    File "/app/.heroku/src/dallinger/dallinger/experiment_server/worker_events.py", line 85, in __call__ 
Sep 23 21:01:44 dlgr-183afda0 app/worker.1:      bonus = self.experiment.bonus(participant=self.participant) 
Sep 23 21:01:44 dlgr-183afda0 app/worker.1:    File "/app/experiment.py", line 1186, in bonus 
Sep 23 21:01:44 dlgr-183afda0 app/worker.1:      data = self._last_state_for_player(participant.id) 
Sep 23 21:01:44 dlgr-183afda0 app/worker.1:    File "/app/experiment.py", line 1749, in _last_state_for_player 
Sep 23 21:01:44 dlgr-183afda0 app/worker.1:      most_recent_grid_state = self.environment.state() 
Sep 23 21:01:44 dlgr-183afda0 app/worker.1:    File "/app/.heroku/src/dallinger/dallinger/nodes.py", line 105, in state 
Sep 23 21:01:44 dlgr-183afda0 app/worker.1:      return max(self.infos(type=State), key=attrgetter('creation_time')) 
Sep 23 21:01:44 dlgr-183afda0 app/worker.1:  ValueError: max() arg is an empty sequence 
Sep 23 21:01:44 dlgr-183afda0 app/worker.1:  2018-09-24 04:01:44,490 ValueError: max() arg is an empty sequence 
Sep 23 21:01:44 dlgr-183afda0 app/worker.1:  Traceback (most recent call last): 
Sep 23 21:01:44 dlgr-183afda0 app/worker.1:    File "/app/.heroku/python/lib/python3.6/site-packages/rq/worker.py", line 793, in perform_job 
Sep 23 21:01:44 dlgr-183afda0 app/worker.1:      rv = job.perform() 
Sep 23 21:01:44 dlgr-183afda0 app/worker.1:    File "/app/.heroku/python/lib/python3.6/site-packages/rq/job.py", line 599, in perform 
Sep 23 21:01:44 dlgr-183afda0 app/worker.1:      self._result = self._execute() 
Sep 23 21:01:44 dlgr-183afda0 app/worker.1:    File "/app/.heroku/python/lib/python3.6/site-packages/rq/job.py", line 605, in _execute 
Sep 23 21:01:44 dlgr-183afda0 app/worker.1:      return self.func(*self.args, **self.kwargs) 
Sep 23 21:01:44 dlgr-183afda0 app/worker.1:    File "/app/.heroku/src/dallinger/dallinger/db.py", line 99, in wrapper 
Sep 23 21:01:44 dlgr-183afda0 app/worker.1:      return func(*args, **kwargs) 
Sep 23 21:01:44 dlgr-183afda0 app/worker.1:    File "/app/.heroku/src/dallinger/dallinger/experiment_server/experiment_server.py", line 1754, in worker_function 
Sep 23 21:01:44 dlgr-183afda0 app/worker.1:      runner() 
Sep 23 21:01:44 dlgr-183afda0 app/worker.1:    File "/app/.heroku/src/dallinger/dallinger/experiment_server/worker_events.py", line 85, in __call__ 
Sep 23 21:01:44 dlgr-183afda0 app/worker.1:      bonus = self.experiment.bonus(participant=self.participant) 
Sep 23 21:01:44 dlgr-183afda0 app/worker.1:    File "/app/experiment.py", line 1186, in bonus 
Sep 23 21:01:44 dlgr-183afda0 app/worker.1:      data = self._last_state_for_player(participant.id) 
Sep 23 21:01:44 dlgr-183afda0 app/worker.1:    File "/app/experiment.py", line 1749, in _last_state_for_player 
Sep 23 21:01:44 dlgr-183afda0 app/worker.1:      most_recent_grid_state = self.environment.state() 
Sep 23 21:01:44 dlgr-183afda0 app/worker.1:    File "/app/.heroku/src/dallinger/dallinger/nodes.py", line 105, in state 
Sep 23 21:01:44 dlgr-183afda0 app/worker.1:      return max(self.infos(type=State), key=attrgetter('creation_time')) 
Sep 23 21:01:44 dlgr-183afda0 app/worker.1:  ValueError: max() arg is an empty sequence 
Sep 23 21:01:44 dlgr-183afda0 app/worker.1:  Traceback (most recent call last): 
Sep 23 21:01:44 dlgr-183afda0 app/worker.1:    File "/app/.heroku/python/lib/python3.6/site-packages/rq/worker.py", line 793, in perform_job 
Sep 23 21:01:44 dlgr-183afda0 app/worker.1:      rv = job.perform() 
Sep 23 21:01:44 dlgr-183afda0 app/worker.1:    File "/app/.heroku/python/lib/python3.6/site-packages/rq/job.py", line 599, in perform 
Sep 23 21:01:44 dlgr-183afda0 app/worker.1:      self._result = self._execute() 
Sep 23 21:01:44 dlgr-183afda0 app/worker.1:    File "/app/.heroku/python/lib/python3.6/site-packages/rq/job.py", line 605, in _execute 
Sep 23 21:01:44 dlgr-183afda0 app/worker.1:      return self.func(*self.args, **self.kwargs) 
Sep 23 21:01:44 dlgr-183afda0 app/worker.1:    File "/app/.heroku/src/dallinger/dallinger/db.py", line 99, in wrapper 
Sep 23 21:01:44 dlgr-183afda0 app/worker.1:      return func(*args, **kwargs) 
Sep 23 21:01:44 dlgr-183afda0 app/worker.1:    File "/app/.heroku/src/dallinger/dallinger/experiment_server/experiment_server.py", line 1754, in worker_function 
Sep 23 21:01:44 dlgr-183afda0 app/worker.1:      runner() 
Sep 23 21:01:44 dlgr-183afda0 app/worker.1:    File "/app/.heroku/src/dallinger/dallinger/experiment_server/worker_events.py", line 85, in __call__ 
Sep 23 21:01:44 dlgr-183afda0 app/worker.1:      bonus = self.experiment.bonus(participant=self.participant) 
Sep 23 21:01:44 dlgr-183afda0 app/worker.1:    File "/app/experiment.py", line 1186, in bonus 
Sep 23 21:01:44 dlgr-183afda0 app/worker.1:      data = self._last_state_for_player(participant.id) 
Sep 23 21:01:44 dlgr-183afda0 app/worker.1:    File "/app/experiment.py", line 1749, in _last_state_for_player 
Sep 23 21:01:44 dlgr-183afda0 app/worker.1:      most_recent_grid_state = self.environment.state() 
Sep 23 21:01:44 dlgr-183afda0 app/worker.1:    File "/app/.heroku/src/dallinger/dallinger/nodes.py", line 105, in state 
Sep 23 21:01:44 dlgr-183afda0 app/worker.1:      return max(self.infos(type=State), key=attrgetter('creation_time')) 
Sep 23 21:01:44 dlgr-183afda0 app/worker.1:  ValueError: max() arg is an empty sequence 
Sep 23 21:01:44 dlgr-183afda0 app/worker.1:  2018-09-24 04:01:44,490 Moving job to 'failed' queue 
```

**Comment by MatthewWilkes** [comment] 2018-09-24 10:17
It looks like this is trying to work out the bonus for a person completing the experiment when there has never been a state info created. Is this during overrecruitment? Maybe the person was passed on as an overrecruit and they managed to submit before the grid loaded for the real players?

The alternative is that the game completed but no State infos were logged.

**Comment by alecpm** [comment] 2018-10-04 16:58
I've been able to reproduce this when over-recruiting. It's possible to reproduce locally in debug mode by using the multi-recruiter and recruiting `num_participants` bots and one `cli`. If you're fast enough you'll hit the you've been over-recruited message before any experiment State infos have been saved.

The fix looks straightforward.

**Comment by jessesnyder** [comment] 2018-11-08 20:52
Fixed; closing.

**Closed by jessesnyder** 2018-11-08 20:52 UTC
Labels: bug
