### ISSUE TITLE
In debug, server opens on  http://0.0.0.0:5001 instead of  http://0.0.0.0:5000

### ISSUE THREAD

**Issue by mongates** [Dallinger/Dallinger#626] opened 2017-06-08 22:57 UTC
We are currently trying to integrate the updated waiting room from the development branch into my current "memoryexpt" demo (which brings people to an instruction page and then into a waiting room) on branch memoryexpt2. When we run this demo, participants are assigned to port 5000, 5001, or 5002. Port 5001 proceeds as expected (participants enter the waiting room). Ports 5000 and 5002 either don't load the page at all ("Safari can’t connect to the server") or it loads the page but shows a "Not Found: The requested URL was not found on the server." page once the participant advances to the waiting room. We see this issue even when we change the number of web dynos or worker dynos. Jordan suggested I run the chatroom demo and see if that works on my branch... so far this demo seems to load participants on port 5000, and I can't press the "Begin" button past the instructions.

EDIT: this problem only occurs when I run debug and the server runs on  http://0.0.0.0:5001 (see below). When it opens with  http://0.0.0.0:5000, there is no problem!

   ____        ____
   / __ \____ _/ / (_)___  ____ ____  _____
  / / / / __ `/ / / / __ \/ __ `/ _ \/ ___/
 / /_/ / /_/ / / / / / / / /_/ /  __/ /
/_____/\__,_/_/_/_/_/ /_/\__, /\___/_/
                        /____/
                                   v3.2.0

                Laboratory automation for
       the behavioral and social sciences.

❯❯ Experiment id is 888d88ea-b659-4c1f-a840-67cb2ce4cdbd
/var/folders/5r/bw67p_8s1mq69xgs7nw7dptw0000gn/T/tmpGXDJu8/888d88ea-b659-4c1f-a840-67cb2ce4cdbd

❯❯ Starting up the server...

❯❯ Server is running on http://0.0.0.0:5001. Press Ctrl+C to exit.

❯❯ Launching the experiment...

❯❯ new recruitment request!

**Comment by jessesnyder** [comment] 2017-06-27 18:59
@mongates As of yesterday, `master` is even more current than `development`, so I'm going to begin researching this based on `master`.

**Comment by mongates** [comment] 2017-06-27 19:04
This error still appears when I've updated to the master branch yesterday evening!

**Comment by jessesnyder** [comment] 2017-06-27 23:47
@mongates I was able to reproduce the problem and come up with a solution. The merits of my fix still need some discussion, but in the meantime you may as well verify that it works for you, too. My branch:  `issues/626-debug-port-mismatch`

I was working with chatroom, but it would be good to know if it fixed memoryexpt too.

**Comment by mongates** [comment] 2017-06-28 00:37
Hello Jesse-- ah, doesn't work: sometimes debug still loads with http://0.0.0.0:5001 on my experiment and has a 5002 browser. This problem only comes up every 2nd or 3rd time-- otherwise debug will run on http://0.0.0.0:5000 and there is no problem.

**Comment by suchow** [comment] 2017-06-28 00:39
@mongates Can you provide evidence that you're on the new branch? e.g., paste the logs starting with `git status` all the way to when you get an error.

**Comment by suchow** [comment] 2017-06-28 00:40
@mongates also make sure the installation is in develop mode (`python setup.py develop`).

**Comment by mongates** [comment] 2017-06-28 00:51
airbears2-10-142-143-10:memoryexpt monica$ git status
On branch issues/626-debug-port-mismatch
Your branch is up-to-date with 'origin/issues/626-debug-port-mismatch'.
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	./

nothing added to commit but untracked files present (use "git add" to track)
airbears2-10-142-143-10:memoryexpt monica$

**Comment by mongates** [comment] 2017-06-28 00:51
airbears2-10-142-143-10:memoryexpt monica$ git status
On branch issues/626-debug-port-mismatch
Your branch is up-to-date with 'origin/issues/626-debug-port-mismatch'.
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	./

nothing added to commit but untracked files present (use "git add" to track)
airbears2-10-142-143-10:memoryexpt monica$ 


________________________________________________________________________________

airbears2-10-142-143-10:memoryexpt monica$ git log
commit 3323e441e3223ae2c09118f54ec5f421d403c1ab
Author: jessesnyder <jesse@rasikaconsulting.com>
Date:   Tue Jun 27 15:44:00 2017 -0700

    Avoid key collision on `os.environ['PORT']`, which is set by Heroku

commit d2fc229c2ea56ada0c6a236b3c3da457f5496dd2
Merge: 94e40e3 09d5651
Author: Jordan Suchow <suchow@post.harvard.edu>
Date:   Mon Jun 26 15:54:41 2017 -0700

    Merge pull request #642 from Dallinger/pyup-update-nltk-3.2.2-to-3.2.4
    
    Update nltk to 3.2.4

commit 09d5651fcf6556479fbbab295261871c64f65623
Author: pyup-bot <github-bot@pyup.io>
Date:   Fri Jun 23 12:03:56 2017 -0700

    Update nltk from 3.2.2 to 3.2.4

commit 94e40e3fd0199a4ca349b817fadb0ba2cdc4d9e5
Merge: ae19365 4e44d04
:

**Comment by jessesnyder** [comment] 2017-06-28 01:25
@mongates @suchow Looks like my branch. I just committed some debugging code I had added when trying to understand the problem. Monica, can you `git pull`, then run the `dallinger debug` session again and upload the output in a text file?

**Comment by mongates** [comment] 2017-06-28 01:36
[run.txt](https://github.com/Dallinger/Dallinger/files/1107314/run.txt)

**Comment by jessesnyder** [comment] 2017-06-28 01:44
@mongates Are you in an experiment directory? Not liking these import errors on startup:
`ImportError: No module named bartlett1932.experiment`

Can you hop on into demos/chatroom and run it there?

**Comment by jessesnyder** [comment] 2017-06-28 01:46
Also, I'm not seeing any of the debugging output from the code in my last commit, which is strange.

**Comment by suchow** [comment] 2017-06-28 01:47
The import errors are a known issue, unrelated to your branch. I’m hoping to track down what introduced them ASAP, but haven’t got a chance.

**Comment by mongates** [comment] 2017-06-28 01:52
Output from git log: 
[git log.txt](https://github.com/Dallinger/Dallinger/files/1107343/git.log.txt)

Ah, dang it-- Jordan, how do I fix the error for chatroom about nltk.chat.eliza again? I know I'm supposed to pip install something something nltk.

**Comment by jessesnyder** [comment] 2017-06-28 01:53
@mongates from inside chatroom directory: `pip install -r requirements.txt`

**Comment by suchow** [comment] 2017-06-28 01:53
`pip install nltk==3.2.4`

**Comment by suchow** [comment] 2017-06-28 01:54
@jessesnyder @mongates no! don't follow jesse's instructions! that'll install the master version of dallinger, not this branch!

**Comment by suchow** [comment] 2017-06-28 01:54
(sorry, overexcited, ha)

**Comment by jessesnyder** [comment] 2017-06-28 01:54
ah, right you are... sorry about that!

**Comment by mongates** [comment] 2017-06-28 02:00
Haha-- no worries, I got it :). I did pip install nltk and it worked.

I just ran the chatroom experiment 5 times, and it loaded the 5000 port correctly each time. 

[loaded on 5000.txt](https://github.com/Dallinger/Dallinger/files/1107357/loaded.on.5000.txt)

Do you want me to push the memoryexpt folder?

**Comment by jessesnyder** [comment] 2017-06-28 02:01
@mongates Promising. Let me have a look at this output.

**Comment by jessesnyder** [comment] 2017-06-28 02:04
Not sure why I still don't see any of my debugging stuff. I assume given how verbiage there is you're running with `--verbose`?

**Comment by davisagli** [comment] 2017-06-28 02:05
What level are you logging at? If it's DEBUG you might need to set log_level = 0 to see it (in config.txt or an environment variable)

**Comment by mongates** [comment] 2017-06-28 02:06
Yes, running verbose, yes debug.

**Comment by jessesnyder** [comment] 2017-06-28 02:08
log_level is 0? :-D

**Comment by mongates** [comment] 2017-06-28 02:09
Do you want me to set that in config.txt in the chatroom and my experiment?

**Comment by jessesnyder** [comment] 2017-06-28 02:10
both, but for now let's keep running the chatroom

**Comment by jessesnyder** [comment] 2017-06-28 02:11
this would probably easier on Slack :)

**Comment by mongates** [comment] 2017-06-28 02:11
KeyError: u'log_level is not a valid configuration key'

**Comment by jessesnyder** [comment] 2017-06-28 02:11
ah, frick. it's `loglevel`.

**Comment by mongates** [comment] 2017-06-28 02:15
JSON error (same thing happened when I tried it again)
[1.txt](https://github.com/Dallinger/Dallinger/files/1107376/1.txt)

**Comment by jessesnyder** [comment] 2017-06-28 02:22
can you run `python` with the virtual environment your running `dallinger` with, then:
```
import sys
import pprint

pprint.pprint(sys.path)
```

Then I need to eat dinner because my brain is fading out.

**Comment by suchow** [comment] 2017-07-05 22:42
Closed by #651.

**Closed by suchow** 2017-07-05 22:42 UTC
Labels: bug
