### ISSUE TITLE
Investigate readthedocs not building properly: 3pts

### ISSUE THREAD

**Issue by pmcharrison** [Dallinger/Dallinger#6756] opened 2024-07-31 15:19 UTC
We think that the [documentation website](https://dallinger.readthedocs.io/en/latest/) is not updated for the latest Dallinger builds, we want to try and fix this.

**Comment by alecpm** [comment] 2024-07-31 17:54
I've submitted a PR to sphinx-js that should resolve the issue and allow #4995 to be merged (though with an updated sphinx-js pin once they release). I think we can build without those docs for now I've confirmed the build process works locally both without sphinx-js and with it enabled using the fork/PR with updated version pin. I think we just need an updated `.readthedocs.yaml`, which I'll try out.

**Comment by alecpm** [comment] 2024-08-01 16:50
It looks like RTD did not automatically build once the config was updated and the PR merged. Unfortunately, that means we'll probably need access to the Dallinger RTD account to get things sorted out.

**Comment by jacobyn** [comment] 2024-08-01 16:55
I am writing an urgent message to @suchow . @suchow if you see this message please respond in any channel.

**Comment by jacobyn** [comment] 2024-08-01 16:57
I found a discussion about it here:
<img width="1080" alt="image" src="https://github.com/user-attachments/assets/b02ead56-251a-46e5-a644-1c4917c7a916">

**Comment by suchow** [comment] 2024-08-01 17:09
Hi, what RTD emails / usernames should I add as maintainers?

**Comment by alecpm** [comment] 2024-08-01 17:18
@suchow alecpm for me and probably fmhoeger for @fmhoeger (assuming he logs in with GitHub SSO).

**Comment by fmhoeger** [comment] 2024-08-01 17:41
Yes, it be would good if I also have access
fmhoeger@mirsem.org / @fmhoeger 

And I guess @pmcharrison too

**Comment by fmhoeger** [comment] 2024-09-16 21:34
Fixed in https://github.com/Dallinger/Dallinger/pull/6904

**Closed by fmhoeger** 2024-09-16 21:34 UTC
Labels: docs
