### ISSUE TITLE
Bartlett 1932 demo notebook broken

### ISSUE THREAD

**Issue by smeylan** [Dallinger/Dallinger#697] opened 2017-08-13 21:03 UTC
## Current Behavior

Line `experiment = dallinger.experiments.Bartlett1932()` errors out, `AttributeError: 'module' object has no attribute 'Bartlett1932'`.

## Steps to Reproduce (for bugs)

1. Fresh dev install from the master branch; no errors in setup
2. Running demos/dlgr/demos/bartlett1932/demo.ipynb (with Dallinger venv kernel)

## Context
Related to changes made for issues #663 or #668? 

## Your Environment

* Dallinger version used: 3.4.0

**Comment by suchow** [comment] 2017-08-13 22:27
Can you change directories in `demos/` and run `python setup.py develop`? That should register the relevant entry points. We'll release a package on PyPI soon.

**Comment by alecpm** [comment] 2017-09-14 08:30
I can't reproduce this error, once the `dlgr.demos` package is installed the API appears to work as expected. Running the demo via `jupyter-notebook demo.ipynb` does not run to completion though. The initial load gives:

    Notebook validation failed: Additional properties are not allowed (u'outputs', u'outputExpanded' were unexpected):
    {
         "source": "# The War of the Ghosts", 
         "cell_type": "markdown", 
         "outputs": [], 
         "outputExpanded": false, 
         "metadata": {
             "collapsed": false
         }
    }

Running through the notebook gives `IOError: not writable` in a `Click` logging method, which may be resolved by #736 and perhaps #714.

**Closed** 2018-04-18 19:13 UTC
Labels: bug
