### ISSUE TITLE
Cache-clearing/ incognito not opening

### ISSUE THREAD

**Issue by lottybrand22** [Dallinger/Dallinger#1361] opened 2018-09-06 08:52 UTC
When running in debug mode you have to clear your cache each time (at least in Chrome) so it can see the changes. To avoid having to do this every 5 minutes, we used to run everything in an incognito window, however just this week Dallinger appears to refuse to open in an incognito window... even if that is the only window I have open. Instead it always automatically opens a regular Chrome window automatically. Same happens to Tom (Morgan) apparently... 
He suggested it could be a Chrome update...? But I haven't changed or updated anything on my machines recently, except the usual pulling from my github repo...

**Comment by vlall** [comment] 2018-09-07 17:31
I don't recall ever getting Dallinger to open the incognito window automatically on my version of chrome (68.0.3440.106) or on Firefox.

**Comment by lottybrand22** [comment] 2018-09-07 18:28
No, Dallinger wouldn't automatically open an incognito window, it would automatically open a new window in incognito mode IF your last opened/ currently active window was in incognito mode. So we used to open a new incognito window before running dallinger --debug, and then it would open in incognito. But now, even if we have incognito windows open just as before, it refuses to open in incognito mode. So, I guess it kind of used to be a 'feature' to be able to use incognito mode, but now we cannot use incognito mode all of a sudden... no matter how hard we try! And I have to keep clearing my cache now so I don't think that problem has been sorted....

**Comment by vlall** [comment] 2018-09-07 19:26
@MatthewWilkes I recall this [PR](https://github.com/Dallinger/Dallinger/pull/816) was intended to make incognito irrelevant and fix the caching issue? I'm wondering if we should add a new story next iteration to reimplement a way to clear caches on launch.

**Comment by MatthewWilkes** [comment] 2018-09-24 10:27
@lottybrand22 What operating system are you using?

@vlall That PR does cause Chrome and Firefox to open in blank profiles, which is similar to opening them in incognito mode except that there is no global state between the windows. In incognito mode as long as one window is open new ones share the incognito state. Here, each window has its own state.

It worked beautifully for me, but unfortunately MacOS uses AppleScript instead of subprocesses in its implementation of `webbrowser.open`, which doesn't allow for passing commands regarding incognito or profiles. Perhaps Chrome has changed its behaviour for the incoming AppleScript commands to always use normal mode, not the last mode.

We can, of course, look at different ways to clear the cache for MacOS, but I think it'll have to be changes to the experiment serving, perhaps caching headers, rather than manipulating the webbrowser calls.

**Comment by lottybrand22** [comment] 2018-09-24 10:30
I'm using macOS High Sierra

**Comment by vlall** [comment] 2019-03-04 22:25
This should be fixed now.

**Closed by vlall** 2019-03-04 22:25 UTC
