### ISSUE TITLE
auto_recruit is set to false automatically in long running apps: 3 pt

### ISSUE THREAD

**Issue by mangl001** [Dallinger/Dallinger#2309] opened 2020-08-13 16:27 UTC
Hi, I've been deploying several experiments in Nori's group using the new version of Dallinger (6.4.0). In three occasions, when I deployed apps that lasted for 24 hours or more I experienced that the app expired automatically (see screenshot of Heroku metrics). When I then look in Heroku/settings/config vars, I can see `auto_recruit=false`. Note that these apps were deployed with `auto_recruit = true` and  `lifetime = 24`.   I also attach two screenshots of the logs when I searched for auto_recruit. I wasn't able to download the entire logs but I can send you the export zip files.
<img width="797" alt="Screenshot 2020-08-12 at 09 37 40" src="https://user-images.githubusercontent.com/33897368/90160698-69e80b00-dd92-11ea-9ff0-d321c8f2268f.png">
<img width="1390" alt="Screenshot 2020-08-12 at 09 44 04" src="https://user-images.githubusercontent.com/33897368/90160710-6c4a6500-dd92-11ea-929c-890318daeba4.png">
<img width="1332" alt="Screenshot 2020-08-12 at 10 13 26" src="https://user-images.githubusercontent.com/33897368/90160714-6eacbf00-dd92-11ea-8c7c-1c310b4c8c3e.png">

.

**Comment by jacobyn** [comment] 2020-08-29 08:39
This issue seems to happens when `clock_on = true`  is set in `config.txt `. The purpose of `clock_on = true` is unclear (to me) and therefore the work around is to disable it (`clock_on = false`). Since this is the cause of this issue, and the workaround is simple and harmless (it does not seem that `clock_on = true`  is important for most use cases), we close the issue. It would be cool if @thomasmorgan  and or @suchow  will clarify at some point what is the original purpose/use case of `clock_on = true`.

**Closed** 2020-08-29 08:40 UTC

**Comment by thomasmorgan** [comment] 2020-08-29 16:29
@jacobyn clock_on determines whether a background process starts that monitors the database for a very specific kind of MTurk error. The error was that under certain conditions MTurk does not sent notifications and this would mangle the database. The clock process checks the database looking for the sign that this error has happened and if it detects it, it tries to fix the database, but if it cannot do so, it pauses recruitment and emails the experimenter letting them know the error has occurred. The email functions no longer work after gmail changed their security setup, but the code is still inside dallinger.

So, you are seeing this issue because the clock process is detecting the MTurk error and pausing recruitment to allow you to go in and fix the database manually. Turning clock_on to false will stop this from happening, but it could lead to worse problems down the line if your database really is in a bad state. This is because the error causes rows that should be failed to not be failed, and so they can be read by future participants. The MTurk error is very rare, which is why you're only seeing it on long running apps. But, AFAIK we've never had issues with false positives, and so I suggest being very careful about turning the clock off.

For the clock process itself see dallinger/dallinger/heroku/clock.py
For the warning emails see dallinger/dallinger/recruiters.py

If auto_recruit is set to false, this is the warning email you would/should have received:
```

cancelled_hit = """Dear experimenter,

This is an automated email from Dallinger. You are receiving this email because
the Dallinger platform has discovered evidence that a notification from Amazon
Web Services failed to arrive at the server. Dallinger has automatically
contacted AWS and has determined the dropped notification was an
abandoned/returned notification (i.e. the participant had returned the
experiment or had run out of time). This is a serious error and so Dallinger has
paused the experiment - expiring the HIT on MTurk and setting auto_recruit to
false. Participants currently playing will be able to finish, however no further
participants will be recruited until you do so manually. We strongly suggest you
use the details below to check the database to make sure the missing
notification has not caused additional problems before resuming. If you are
receiving a lot of these emails this suggests something is wrong with your
experiment code.

Best,

The Dallinger dev. team.

Error details:
Assignment: {s.assignment_id}

Allowed time (minutes): {s.allowed_minutes:.0f}
Time since participant started: {s.active_minutes:.0f}
"""
```
